crustdata:
  keyword: "HubSpot"
  date_posted: "past-24h"
  max_comments: 50
  max_posts: 10

  profiles:
    - https://www.linkedin.com/in/yaminirangan/
    - https://www.linkedin.com/in/dharmesh/
  profile_posts_limit: 5

google_sheets:
  spreadsheet_id: "11kQchHbp88XcWRvm4SETSVvD3SdWtpChAq7qS9aI1l8"
  keyword_tab: "Keyword Intel"
  keyword_archive_tab: "Keyword Intel Archive"
  profile_tab: "Profile Posts"
  profile_archive_tab: "Profile Posts Archive"
